using System.Text;
using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace Spek.Compiler.Proto;

/// <summary>
/// Turns a Protocol Buffer descriptor (as produced by
/// <c>protoc --descriptor_set_out</c> or by <c>Grpc.Tools</c>'s
/// MSBuild integration) into Spek source code: one
/// <c>channel</c> declaration per <c>service</c>, one
/// <c>message</c> declaration per referenced message type.
/// The output is a valid <c>.spek</c> source string that can be
/// fed to <see cref="Spek.Compiler.Parser.SpekCompilation.Create"/>
/// alongside hand-written sources.
///
/// <para>
/// The synthesizer deliberately produces *Spek source* rather than
/// AST nodes directly. Two reasons:
/// </para>
/// <list type="number">
///   <item>The output is human-readable. Writing it to
///         <c>obj/Spek.Generated/&lt;ChannelName&gt;.g.spek</c>
///         gives users a real file they can inspect, debug, and
///         have IDE go-to-definition land in. AST-only synthesis
///         hides the intermediate representation.</item>
///   <item>The compiler's existing semantic analysis treats the
///         generated channel identically to a hand-written one —
///         no special "synthesized" code path, no risk of
///         divergence between the two ingestion routes.</item>
/// </list>
///
/// <para>
/// Streaming RPCs (<c>stream</c> in the request or response) are
/// detected and reported via <see cref="Diagnostics"/>; the
/// service is still emitted but with the streaming methods
/// commented out and a TODO marker. The synthesizer ships unary-only;
/// streaming patterns rejoin in a follow-up.
/// </para>
/// </summary>
public sealed class ProtoChannelSynthesizer
{
    /// <summary>
    /// Diagnostics surfaced during synthesis — non-fatal warnings
    /// (skipped streaming RPCs) and fatal errors (missing service,
    /// malformed descriptor). The caller decides whether to fail
    /// the build based on severity.
    /// </summary>
    public IReadOnlyList<SynthesisDiagnostic> Diagnostics => _diagnostics;
    private readonly List<SynthesisDiagnostic> _diagnostics = new();

    /// <summary>
    /// Reads the binary <see cref="FileDescriptorSet"/> at
    /// <paramref name="descriptorPath"/>, extracts the service
    /// named <paramref name="channelName"/> (which becomes the
    /// Spek channel of the same name), and emits the synthesised
    /// Spek source. The <paramref name="protoSourceLabel"/> is
    /// included verbatim in the auto-generated header so the
    /// "edit this file instead" pointer matches the user's view of
    /// the proto.
    /// </summary>
    public string Synthesize(
        string descriptorPath,
        string channelName,
        string protoSourceLabel)
    {
        ArgumentNullException.ThrowIfNull(descriptorPath);
        ArgumentNullException.ThrowIfNull(channelName);
        ArgumentNullException.ThrowIfNull(protoSourceLabel);

        // The on-disk format is a FileDescriptorSet (what
        // `protoc --descriptor_set_out` produces). Parse it, then
        // hand each contained FileDescriptorProto's serialized bytes
        // to FileDescriptor.BuildFromByteStrings — the Reflection API
        // resolves cross-file references and yields ServiceDescriptors.
        var bytes   = File.ReadAllBytes(descriptorPath);
        var fileSet = FileDescriptorSet.Parser.ParseFrom(bytes);
        var perFileBytes = fileSet.File
            .Select(fd => Google.Protobuf.ByteString.CopyFrom(fd.ToByteArray()))
            .ToList();
        var descriptors = FileDescriptor.BuildFromByteStrings(perFileBytes);

        // Find the service in any of the included files. Multi-file
        // descriptor sets can carry imports; the service we want is
        // the one named <channelName>.
        ServiceDescriptor? service = null;
        foreach (var fd in descriptors)
        {
            foreach (var s in fd.Services)
            {
                if (s.Name == channelName) { service = s; break; }
            }
            if (service is not null) break;
        }

        if (service is null)
        {
            _diagnostics.Add(SynthesisDiagnostic.Error(
                $"No service named '{channelName}' in descriptor '{descriptorPath}'."));
            return EmitErrorPlaceholder(channelName, protoSourceLabel);
        }

        return EmitChannelSource(service, protoSourceLabel);
    }

    // ─── Spek source emission ──────────────────────────────────────────

    private string EmitChannelSource(ServiceDescriptor service, string protoSourceLabel)
    {
        var sb = new StringBuilder();
        EmitAutoGeneratedHeader(sb, protoSourceLabel);

        // Collect message types reachable from the service's RPCs.
        // We synthesise a Spek `message` decl for each so the
        // generated channel doesn't reference unknown names.
        var inputs  = new List<MessageDescriptor>();
        var outputs = new List<MessageDescriptor>();
        var seenMessages = new HashSet<string>(StringComparer.Ordinal);

        foreach (var method in service.Methods)
        {
            if (method.IsClientStreaming || method.IsServerStreaming)
            {
                _diagnostics.Add(SynthesisDiagnostic.Warning(
                    $"Skipped streaming RPC '{service.Name}.{method.Name}' — " +
                    $"only unary RPCs are supported."));
                continue;
            }
            if (seenMessages.Add(method.InputType.FullName))  inputs.Add(method.InputType);
            if (seenMessages.Add(method.OutputType.FullName)) outputs.Add(method.OutputType);
        }

        // Emit message decls first so the channel's `on Foo;` /
        // `emits Bar;` references resolve.
        foreach (var msg in inputs.Concat(outputs))
            EmitMessageDecl(sb, msg);

        sb.AppendLine();
        sb.Append("channel ").AppendLine(service.Name);
        sb.AppendLine("{");
        foreach (var method in service.Methods)
        {
            if (method.IsClientStreaming || method.IsServerStreaming)
            {
                sb.Append("    // TODO(streaming): on ").Append(method.InputType.Name)
                  .Append(';').AppendLine();
                continue;
            }
            sb.Append("    on ").Append(method.InputType.Name).Append(';').AppendLine();
        }
        // Emit each unique response type as `emits`.
        sb.AppendLine();
        var emittedSeen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var method in service.Methods)
        {
            if (method.IsClientStreaming || method.IsServerStreaming) continue;
            var name = method.OutputType.Name;
            if (emittedSeen.Add(name))
                sb.Append("    emits ").Append(name).Append(';').AppendLine();
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMessageDecl(StringBuilder sb, MessageDescriptor msg)
    {
        sb.Append("message ").Append(msg.Name).Append('(');
        for (int i = 0; i < msg.Fields.InDeclarationOrder().Count; i++)
        {
            var field = msg.Fields.InDeclarationOrder()[i];
            if (i > 0) sb.Append(", ");
            sb.Append(SpekFieldType(field)).Append(' ').Append(field.Name);
        }
        sb.AppendLine(");");
    }

    /// <summary>
    /// Maps a proto field type to its Spek-source equivalent.
    /// Covers the proto3 scalar set; nested messages emit as their
    /// Spek-side type name (the synthesizer assumes the message is
    /// also synthesized into the same source file). Repeated and
    /// map fields are not yet supported — they raise a synthesis
    /// warning and emit as <c>object</c>.
    /// </summary>
    private static string SpekFieldType(FieldDescriptor field)
    {
        if (field.IsRepeated || field.IsMap) return "object";   // TODO follow-up

        return field.FieldType switch
        {
            FieldType.Bool                    => "bool",
            FieldType.String                  => "string",
            FieldType.Int32 or FieldType.SInt32 or FieldType.SFixed32 => "int",
            FieldType.Int64 or FieldType.SInt64 or FieldType.SFixed64 => "long",
            FieldType.UInt32 or FieldType.Fixed32 => "uint",
            FieldType.UInt64 or FieldType.Fixed64 => "ulong",
            FieldType.Float                   => "float",
            FieldType.Double                  => "double",
            FieldType.Bytes                   => "byte[]",
            FieldType.Message                 => field.MessageType.Name,
            FieldType.Enum                    => field.EnumType.Name,
            _                                 => "object",
        };
    }

    private static void EmitAutoGeneratedHeader(StringBuilder sb, string protoSourceLabel)
    {
        sb.AppendLine("// <auto-generated>");
        sb.Append("//   Source: ").AppendLine(protoSourceLabel);
        sb.AppendLine("//   This file was generated from a Protocol Buffer definition by");
        sb.AppendLine("//   the Spek compiler. DO NOT EDIT — changes are overwritten on");
        sb.AppendLine("//   the next build. To modify the channel's contract, edit");
        sb.Append("//   ").Append(protoSourceLabel).AppendLine(" and rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
    }

    private string EmitErrorPlaceholder(string channelName, string protoSourceLabel)
    {
        var sb = new StringBuilder();
        EmitAutoGeneratedHeader(sb, protoSourceLabel);
        sb.AppendLine("// SYNTHESIS FAILED — see compiler diagnostics for details.");
        sb.AppendLine("// This placeholder exists so downstream sources referencing");
        sb.Append("// channel ").Append(channelName).AppendLine(" still parse.");
        sb.Append("channel ").Append(channelName).AppendLine(" { }");
        return sb.ToString();
    }
}

/// <summary>
/// Diagnostic produced during proto-to-Spek synthesis.
/// Mirrors the shape of <see cref="Spek.Compiler.Semantic.Diagnostic"/>
/// without taking a dependency on the Semantic namespace at the
/// proto layer (the synthesizer deliberately stays close to the
/// proto reflection types so the layering is one-way).
/// </summary>
public sealed record SynthesisDiagnostic(string Severity, string Message)
{
    public static SynthesisDiagnostic Error(string msg)   => new("Error",   msg);
    public static SynthesisDiagnostic Warning(string msg) => new("Warning", msg);
}
