using Spek.Compiler.Emit;
using Spek.Compiler.Parser;
using Xunit;

namespace Spek.Tests.Emit;

/// <summary>
/// A persistent actor with no explicit <c>on Restore</c> gets an
/// auto-generated symmetric <c>OnRestore</c> that rehydrates each captured field
/// (mirroring <c>CaptureFields</c>). Save-automatic / restore-manual was a silent
/// data-loss trap (persist 3, rehydrate 0). An explicit <c>on Restore</c> still wins;
/// transient/retired fields are excluded, exactly as from capture.
/// </summary>
public sealed class AutoRestoreEmitTests
{
    private static string Emit(string src)
    {
        var parse = SpekCompiler.Parse(src);
        Assert.True(parse.Success,
            string.Join("\n", parse.Diagnostics.Select(d => $"  {d.Code} {d.Message}")));
        return new FileEmitter().Emit(parse.Tree!);
    }

    [Fact]
    public void NoExplicitRestore_AutoGeneratesOnRestore()
    {
        const string src = """
            message Go();
            actor A
            {
                int count = 0;
                transient int calls = 0;
                init() { become R; }
                behavior R { on Go => { count = count + 1; calls = calls + 1; persist; } }
            }
            """;
        var cs = Emit(src);
        Assert.Contains("protected override void OnRestore(", cs);
        Assert.Contains("_count = ", cs);
        Assert.Contains("Get<int>(\"count\")", cs);
        // `calls` is transient — it's never a snapshot key (not captured, not restored).
        // (It still appears as `_calls` in the handler body, which is fine.)
        Assert.DoesNotContain("\"calls\"", cs);
    }

    [Fact]
    public void ExplicitRestore_Wins_NoAutoGeneratedDuplicate()
    {
        const string src = """
            message Go();
            actor A
            {
                int count = 0;
                init() { become R; }
                behavior R { on Go => { count = count + 1; persist; } }
                on Restore(Snapshot s) => { count = s.Get<int>("count") + 100; }
            }
            """;
        var cs = Emit(src);
        var occurrences = cs.Split("void OnRestore(").Length - 1;
        Assert.Equal(1, occurrences);     // exactly one — the explicit, no auto duplicate
        Assert.Contains("+ 100", cs);     // the explicit body
    }

    [Fact]
    public void NonPersistentActor_NoOnRestore()
    {
        const string src = """
            message Go();
            actor A
            {
                int count = 0;
                init() { become R; }
                behavior R { on Go => { count = count + 1; } }
            }
            """;
        var cs = Emit(src);
        Assert.DoesNotContain("void OnRestore(", cs);
    }
}
