using Google.Protobuf;
using Google.Protobuf.Reflection;
using Spek.Compiler.Parser;
using Spek.Compiler.Proto;
using Xunit;

namespace Spek.Tests.Compiler;

/// <summary>
/// Synthesizer that turns a Protocol Buffer descriptor
/// (binary FileDescriptorSet, as produced by protoc) into Spek
/// source. Tests here build the descriptor programmatically via
/// the Google.Protobuf reflection types so the test suite doesn't
/// depend on a protoc executable being on the developer's path.
/// </summary>
public sealed class ProtoChannelSynthesizerTests
{
    /// <summary>
    /// Builds an in-memory FileDescriptorSet, serialises it, and
    /// writes to a temp file. Returns the temp file path so the
    /// synthesizer's File.ReadAllBytes call works without any
    /// external tooling.
    /// </summary>
    private static string WriteDescriptorToTempFile(FileDescriptorProto fileProto)
    {
        var fileSet = new FileDescriptorSet();
        fileSet.File.Add(fileProto);
        var bytes = fileSet.ToByteArray();
        var path = Path.GetTempFileName();
        File.WriteAllBytes(path, bytes);
        return path;
    }

    /// <summary>
    /// Mints a small "user_api.proto"-equivalent FileDescriptorProto
    /// with a service, two unary RPCs, and the message types they
    /// reference. Tests use this as the canonical fixture; each
    /// test can reach in to mutate fields if it needs a variant.
    /// </summary>
    private static FileDescriptorProto BuildUserApiDescriptor()
    {
        var file = new FileDescriptorProto
        {
            Name    = "user_api.proto",
            Syntax  = "proto3",
            Package = "userapi",
        };

        var getUserMsg = new DescriptorProto { Name = "GetUser" };
        getUserMsg.Field.Add(new FieldDescriptorProto
        {
            Name     = "id",
            Number   = 1,
            Type     = FieldDescriptorProto.Types.Type.String,
            Label    = FieldDescriptorProto.Types.Label.Optional,
            JsonName = "id",
        });

        var createUserMsg = new DescriptorProto { Name = "CreateUser" };
        createUserMsg.Field.Add(new FieldDescriptorProto
        {
            Name     = "name",  Number = 1,
            Type     = FieldDescriptorProto.Types.Type.String,
            Label    = FieldDescriptorProto.Types.Label.Optional,
            JsonName = "name",
        });
        createUserMsg.Field.Add(new FieldDescriptorProto
        {
            Name     = "email", Number = 2,
            Type     = FieldDescriptorProto.Types.Type.String,
            Label    = FieldDescriptorProto.Types.Label.Optional,
            JsonName = "email",
        });

        var userMsg = new DescriptorProto { Name = "User" };
        userMsg.Field.Add(new FieldDescriptorProto { Name = "id",    Number = 1, Type = FieldDescriptorProto.Types.Type.String, Label = FieldDescriptorProto.Types.Label.Optional, JsonName = "id"    });
        userMsg.Field.Add(new FieldDescriptorProto { Name = "name",  Number = 2, Type = FieldDescriptorProto.Types.Type.String, Label = FieldDescriptorProto.Types.Label.Optional, JsonName = "name"  });
        userMsg.Field.Add(new FieldDescriptorProto { Name = "email", Number = 3, Type = FieldDescriptorProto.Types.Type.String, Label = FieldDescriptorProto.Types.Label.Optional, JsonName = "email" });

        file.MessageType.Add(getUserMsg);
        file.MessageType.Add(createUserMsg);
        file.MessageType.Add(userMsg);

        var service = new ServiceDescriptorProto { Name = "UserApi" };
        service.Method.Add(new MethodDescriptorProto
        {
            Name       = "GetUser",
            InputType  = ".userapi.GetUser",
            OutputType = ".userapi.User",
        });
        service.Method.Add(new MethodDescriptorProto
        {
            Name       = "CreateUser",
            InputType  = ".userapi.CreateUser",
            OutputType = ".userapi.User",
        });
        file.Service.Add(service);
        return file;
    }

    // ─── Basic synthesis ───────────────────────────────────────────────

    [Fact]
    public void Synthesizes_AutoGeneratedHeader_PointingAtProtoSource()
    {
        var path = WriteDescriptorToTempFile(BuildUserApiDescriptor());
        try
        {
            var src = new ProtoChannelSynthesizer().Synthesize(path, "UserApi", "user_api.proto");

            Assert.Contains("<auto-generated>",  src);
            Assert.Contains("Source: user_api.proto", src);
            Assert.Contains("DO NOT EDIT",       src);
            Assert.Contains("user_api.proto and rebuild", src);
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Synthesizes_ChannelDecl_WithOnAndEmits()
    {
        var path = WriteDescriptorToTempFile(BuildUserApiDescriptor());
        try
        {
            var src = new ProtoChannelSynthesizer().Synthesize(path, "UserApi", "user_api.proto");

            Assert.Contains("channel UserApi", src);
            Assert.Contains("on GetUser;",    src);
            Assert.Contains("on CreateUser;", src);
            Assert.Contains("emits User;",    src);
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Synthesizes_MessageDecls_WithCorrectFieldTypes()
    {
        var path = WriteDescriptorToTempFile(BuildUserApiDescriptor());
        try
        {
            var src = new ProtoChannelSynthesizer().Synthesize(path, "UserApi", "user_api.proto");

            Assert.Contains("message GetUser(string id);",                              src);
            Assert.Contains("message CreateUser(string name, string email);",           src);
            Assert.Contains("message User(string id, string name, string email);",      src);
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Synthesized_Source_ParsesAsValidSpek()
    {
        // The output of synthesis must round-trip through the
        // existing Spek parser. If it doesn't, the synthesizer is
        // generating malformed source.
        var path = WriteDescriptorToTempFile(BuildUserApiDescriptor());
        try
        {
            var src    = new ProtoChannelSynthesizer().Synthesize(path, "UserApi", "user_api.proto");
            var parsed = SpekCompiler.Parse(src);

            Assert.True(parsed.Success,
                "Synthesized source did not parse: " +
                string.Join("\n", parsed.Diagnostics.Select(d => $"{d.Code} {d.Line}:{d.Column} {d.Message}")) +
                "\n--- emitted ---\n" + src);
        }
        finally { File.Delete(path); }
    }

    // ─── Streaming detection ───────────────────────────────────────────

    [Fact]
    public void StreamingRpc_EmitsWarning_AndCommentsOutMethod()
    {
        var file = BuildUserApiDescriptor();
        // Make GetUser a server-streaming call.
        file.Service[0].Method[0].ServerStreaming = true;

        var path = WriteDescriptorToTempFile(file);
        try
        {
            var synth = new ProtoChannelSynthesizer();
            var src   = synth.Synthesize(path, "UserApi", "user_api.proto");

            Assert.Contains(synth.Diagnostics, d => d.Severity == "Warning"
                && d.Message.Contains("UserApi.GetUser"));
            Assert.Contains("// TODO(streaming): on GetUser;", src);
            // Non-streaming method still generated.
            Assert.Contains("on CreateUser;", src);
        }
        finally { File.Delete(path); }
    }

    // ─── Error cases ───────────────────────────────────────────────────

    [Fact]
    public void MissingService_EmitsErrorDiagnostic_AndPlaceholderChannel()
    {
        var path = WriteDescriptorToTempFile(BuildUserApiDescriptor());
        try
        {
            var synth = new ProtoChannelSynthesizer();
            var src   = synth.Synthesize(path, "DoesNotExist", "user_api.proto");

            Assert.Contains(synth.Diagnostics, d => d.Severity == "Error"
                && d.Message.Contains("DoesNotExist"));
            // Placeholder is still parseable so downstream sources
            // referencing the channel name don't cascade-fail.
            Assert.Contains("channel DoesNotExist { }", src);
        }
        finally { File.Delete(path); }
    }

    // ─── End-to-end with Spek compilation ──────────────────────────────

    [Fact]
    public void Synthesized_Source_CompilesAlongsideHandWrittenActor()
    {
        var path = WriteDescriptorToTempFile(BuildUserApiDescriptor());
        try
        {
            var synthesized = new ProtoChannelSynthesizer().Synthesize(
                path, "UserApi", "user_api.proto");

            // Hand-written actor that implements the synthesized channel.
            var actorSrc = """
                actor UserService : UserApi
                {
                    on GetUser g    => return new User(g.id, "Alice", "alice@example.com");
                    on CreateUser c => return new User("u-" + c.name, c.name, c.email);
                }
                """;

            var compilation = SpekCompilation.Create(new[]
            {
                ("user_api.g.spek", synthesized),
                ("user_service.spek", actorSrc),
            });

            Assert.True(compilation.Success,
                "Combined compilation failed: " +
                string.Join("\n", compilation.Diagnostics.Select(d => $"{d.Code} {d.Line}:{d.Column} {d.Message}")));
        }
        finally { File.Delete(path); }
    }
}
