using Spek.Compiler.AST;
using Spek.Compiler.Semantic;

namespace Spek.Compiler.Emit;

/// <summary>
/// Top-level orchestrator: walks a <see cref="SpekFile"/> and emits a complete .g.cs file.
/// </summary>
public sealed class FileEmitter
{
    /// <param name="file">The parsed file to emit.</param>
    /// <param name="symbols">Combined symbol table for multi-file compilations.</param>
    /// <param name="sourceFileName">When given, the emitted C# carries
    /// <c>#line</c> directives mapping statements back to this .spek path, so
    /// Roslyn diagnostics and debugger stepping land on the Spek source
    /// instead of the generated file. Null (the default) emits no directives.</param>
    /// <param name="asyncReferencePaths">Extra assembly paths fed to the
    /// invisible-async pass so it can auto-await Task-returning APIs from
    /// outside the BCL (e.g. AspNetCore). Null uses the BCL alone.</param>
    public string Emit(SpekFile file, SymbolTable? symbols = null, string? sourceFileName = null,
        IReadOnlyList<string>? asyncReferencePaths = null, bool emitTests = false)
    {
        // Build a per-file symbol table if the caller didn't provide one.
        // Callers with a multi-file <see cref="SpekCompilation"/> pass their
        // combined table so cross-file ask reply-type inference works.
        symbols ??= SymbolTable.Build(file);

        // Convention: in a test project (emitTests), a module/class whose name ends
        // in `Tests` is a test container — its public methods emit as tests.
        var hasConventionTests = emitTests && file.Declarations.Any(IsTestContainer);

        // Pure-data files — only enums and messages whose fields name no Spek
        // runtime type — reference nothing from the Spek namespaces, so skip the
        // Spek usings. That lets a dependency-light DTO/enum package be authored
        // in Spek without taking a reference on Spek.Runtime purely to satisfy an
        // otherwise-unused `using`. Anything richer (an actor, class, module,
        // channel, or a message field naming a Spek type) still gets them.
        var needsSpekUsings =
            file.Declarations.Any(d => d is not (MessageDecl or EnumDecl))
            || file.Declarations.OfType<MessageDecl>()
                .SelectMany(m => m.Fields)
                .Any(f => TypeMentionsSpek(f.Type));

        var writer         = new CSharpWriter();
        if (sourceFileName is not null) writer.EnableSourceMapping(sourceFileName);
        var msgEmitter     = new MessageEmitter(writer);
        var actorEmitter   = new ActorEmitter(writer, symbols);
        var moduleEmitter  = new ModuleEmitter(writer, symbols);
        var classEmitter   = new ClassEmitter(writer, symbols);

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Generic;");
        writer.Line("using System.Threading.Tasks;");
        if (needsSpekUsings)
        {
            writer.Line("using Spek;");              // Fundamentals — ActorBase, ActorRef, FailureDirective, Outcome, clocks
            writer.Line("using Spek.Runtime;");      // engine internals — ActorSystem, runtime types
            writer.Line("using Spek.Persistence;");  // Snapshot, ISnapshotStore (used in `on Restore` handlers)
        }
        if (hasConventionTests)
        {
            writer.Line("using System.Linq;");   // Count/Any/Select over collections in test assertions
            writer.Line("using Spek.Testing;");  // TestActorSystem, TestProbe, [SpekTest]
        }
        writer.Line();

        foreach (var u in file.Usings)
        {
            writer.Line($"using {u.Name};");

            // `using Spek.Streams;` in Spek source enables bare
            // factory calls (`debounce(500)`, `throttle(16)`, ...) by
            // also pulling in the lowercase factories statically. C#
            // namespace imports don't do this on their own.
            if (u.Name.ToString() == "Spek.Streams")
                writer.Line("using static Spek.Streams.StreamOperators;");
        }

        if (file.Usings.Count > 0)
            writer.Line();

        if (file.Namespace is not null)
        {
            writer.Line($"namespace {file.Namespace.Name};");
            writer.Line();
        }

        foreach (var decl in file.Declarations)
        {
            switch (decl)
            {
                case MessageDecl msg:
                    msgEmitter.Emit(msg);
                    break;

                case EnumDecl en:
                    EmitEnum(en, writer);
                    break;

                case ActorDecl actor:
                    actorEmitter.Emit(actor);
                    break;

                case ModuleDecl module:
                    // Modules emit as C# static classes; nested
                    // modules emit as nested static classes inside the
                    // outer one. Methods inside emit as static methods.
                    // In a test project, a `*Tests` module is a test container.
                    if (emitTests && module.Name.EndsWith("Tests", StringComparison.Ordinal))
                        EmitTestContainer(module, writer, symbols);
                    else
                        moduleEmitter.Emit(module);
                    break;

                case ClassDecl cls:
                    // A mutable, single-owner class emits as a plain
                    // C# instance class (fields + init-constructor + methods).
                    // In a test project, a `*Tests` class is a test container.
                    if (emitTests && cls.Name.EndsWith("Tests", StringComparison.Ordinal))
                        EmitTestContainer(cls, writer, symbols);
                    else
                        classEmitter.Emit(cls);
                    break;

                case SharedRegionDecl sr:
                    EmitSharedRegion(sr, writer);
                    break;

                case ProgramDecl prog:
                    EmitProgram(prog, writer);
                    break;

                case ChannelDecl ch:
                    // Channels emit as marker interfaces with
                    // [SpekChannelMetadata] attached so hosting
                    // adapters (REST, future gRPC) can reflect over
                    // the channel's input/emit message sets at
                    // runtime. Channels remain compile-time contracts
                    // for the most part — there are no methods on the
                    // emitted interface, no inheritance to enforce
                    // at runtime — but the metadata is real C# the
                    // adapters can read.
                    EmitChannel(ch, symbols, writer);
                    break;

                case InterfaceDecl iface:
                    // The class-side contract emits as a plain C# interface:
                    // signatures only, base interfaces passed through verbatim.
                    EmitInterface(iface, writer);
                    break;
            }
        }

        // Invisible async. The provisional C# above emits calls
        // without await; this pass inserts auto-await on Task-returning
        // calls and marks the enclosing methods async, iterating to a
        // fixpoint so async-ness propagates through Spek functions. It's a
        // no-op (returns the string unchanged) when nothing is awaitable.
        return AsyncRewriter.Rewrite(writer.ToString(), extraReferencePaths: asyncReferencePaths);
    }

    /// <summary>
    /// Emits a `shared X { ... }` region as a C# class deriving
    /// from <c>Spek.SharedRegion</c>. Phase 1 just emits the field list
    /// with public visibility (so attached actors can reach the fields
    /// through the lazy-property accessor on the actor). Init blocks,
    /// persistence clauses, and reader/writer-only modes are deferred
    /// to follow-up commits — the generated class is ready to receive
    /// them additively.
    /// </summary>
    private static void EmitSharedRegion(SharedRegionDecl sr, CSharpWriter w)
    {
        var vis = sr.Visibility switch
        {
            Visibility.Public    => "public",
            Visibility.Internal  => "internal",
            Visibility.Protected => "protected",
            Visibility.Private   => "private",
            _                    => "internal",
        };

        // Phase 3 — pick the runtime base class based on the
        // optional capability marker. Unknown markers fall through to
        // SharedRegion; semantic analysis will eventually surface
        // them as a CE (not implemented in Phase 3 — Persisted is
        // the only capability we know).
        var baseType = sr.BaseCapability switch
        {
            "Persisted"   => "Spek.PersistedRegion",
            // "Replicated" / "EventSourced" / "Crdt" reserved.
            null          => "Spek.SharedRegion",
            _             => "Spek.SharedRegion",
        };

        // Regions with a `term { }` block also implement
        // IAsyncDisposable so external consumers can use `await using`.
        // Internal disposal is driven by ActorSystem.Dispose, which
        // walks _regionConstructionOrder LIFO and calls OnTerm() on
        // each region.
        var bases = sr.Term is not null
            ? $"{baseType}, System.IAsyncDisposable"
            : baseType;

        w.Line($"{vis} sealed class {sr.Name} : {bases}");
        w.Line("{");
        w.Indent();

        // CE0108: region field visibility now flows through to
        // the emitted C# class. A field declared `private` is private
        // to the region (set in init or used by other fields, not
        // accessible to attaching actors). The default — when the
        // user wrote no modifier — is `public` so attaching actors
        // can read/write the field as before. `internal` /
        // `protected` emit verbatim.
        //
        // Init bodies use `selfIsThis: true` so `self.Name = "..."`
        // emits as `this.Name = "..."` against the base class's
        // settable `Name` property.
        var exprEmitter = new ExpressionEmitter(new HashSet<string>(), selfIsThis: true);
        foreach (var f in sr.Fields)
        {
            var fieldVis = f.IsExplicitVisibility
                ? FieldVisibilityKeyword(f.Visibility)
                : "public";
            if (f.Initializer is not null)
                w.Line($"{fieldVis} {f.Type} {f.Name} = {exprEmitter.Emit(f.Initializer)};");
            else
                // Phase 3 — class fields without explicit
                // initializers default to `new()` so missing-from-
                // snapshot restores fall back to a constructed
                // instance (per Q1(b) decision in the design conv).
                // For value types, target-typed `new()` produces
                // `default(T)` which is what users expect.
                w.Line($"{fieldVis} {f.Type} {f.Name} = new();");
        }

        // Phase 2 — emit the optional `init { ... }` block as an
        // Initialize() override. The runtime calls it once on first
        // reader/writer access; concurrent first-callers wait until
        // it completes, so user code may freely mutate region fields
        // without worrying about partial-state visibility.
        if (sr.Init is not null)
        {
            w.Line();
            w.Line("protected override void Initialize()");
            var stmtEmitter = new StatementEmitter(w, exprEmitter);
            stmtEmitter.EmitBlock(sr.Init);
        }

        // Phase 3 — emit the persistence shape for : Persisted
        // regions: CaptureFields() returns every field as a key/value
        // pair; RestoreFields(Snapshot) overwrites only the keys that
        // are present in the snapshot. Missing keys keep the
        // initialiser values (graceful additive schema rule).
        if (sr.BaseCapability == "Persisted")
        {
            EmitPersistedOverrides(sr, w);
        }

        // `term { }` block emits as an OnTerm override plus a
        // DisposeAsync wrapper for external consumers. Runtime
        // invocation is wired through ActorSystem.Dispose, which calls
        // OnTerm() on each region in reverse construction order.
        if (sr.Term is not null)
        {
            w.Line();
            w.Line("protected override void OnTerm()");
            w.Line("{");
            w.Indent();
            var stmtEmitter = new StatementEmitter(w, exprEmitter);
            foreach (var s in sr.Term.Statements) stmtEmitter.EmitStatement(s);
            w.Dedent();
            w.Line("}");
            w.Line();
            w.Line("public System.Threading.Tasks.ValueTask DisposeAsync()");
            w.Line("{");
            w.Indent();
            w.Line("OnTerm();");
            w.Line("return System.Threading.Tasks.ValueTask.CompletedTask;");
            w.Dedent();
            w.Line("}");
        }

        w.Dedent();
        w.Line("}");
        w.Line();
    }

    /// <summary>
    /// Maps a Spek visibility modifier to its C# keyword for
    /// region field emission. Used by CE0108: when the user writes
    /// an explicit modifier, that modifier flows through to the
    /// generated class.
    /// </summary>
    private static string FieldVisibilityKeyword(Visibility v) => v switch
    {
        Visibility.Public    => "public",
        Visibility.Internal  => "internal",
        Visibility.Protected => "protected",
        Visibility.Private   => "private",
        _                    => "public",
    };

    /// <summary>
    /// Emits a Spek channel as a marker C# interface decorated
    /// with <c>[Spek.Hosting.SpekChannelMetadata]</c> so reflection at
    /// runtime can recover the channel's input and emit message sets.
    /// The interface itself has no members; actors implementing the
    /// channel emit as <c>: ChannelName</c> on the C# class so the
    /// implementation relationship is real (not just a Spek-level
    /// compile-time check).
    /// </summary>
    private static void EmitChannel(ChannelDecl ch, SymbolTable symbols, CSharpWriter w)
    {
        // Walk the channel's flattened input/emit set, including
        // anything inherited from base channels. The symbol table's
        // existing channel resolution handles the linearisation
        // (CE0094 already prevents cycles).
        var inputs = new List<string>();
        var emits  = new List<string>();
        var emitsAny = false;
        var seenInputs = new HashSet<string>(StringComparer.Ordinal);
        var seenEmits  = new HashSet<string>(StringComparer.Ordinal);

        CollectChannelMembers(ch, symbols, inputs, emits, ref emitsAny, seenInputs, seenEmits);

        var vis = ch.Visibility switch
        {
            Visibility.Public    => "public",
            Visibility.Internal  => "internal",
            _                    => "internal",
        };

        var inputArr = inputs.Count > 0
            ? "new global::System.Type[] { " + string.Join(", ", inputs.Select(i => $"typeof({i})")) + " }"
            // Empty *array creation* (not Array.Empty<>(), a method call) —
            // attribute arguments only allow constants, typeof, and array
            // creation, so a method call here is a CS0182 in the emitted C#.
            : "new global::System.Type[] { }";
        var emitArr = emits.Count > 0
            ? "new global::System.Type[] { " + string.Join(", ", emits.Select(e => $"typeof({e})")) + " }"
            // Empty *array creation* (not Array.Empty<>(), a method call) —
            // attribute arguments only allow constants, typeof, and array
            // creation, so a method call here is a CS0182 in the emitted C#.
            : "new global::System.Type[] { }";

        w.Line($"[global::Spek.Hosting.SpekChannelMetadata(");
        w.Line($"    inputs: {inputArr},");
        w.Line($"    emits: {emitArr},");
        w.Line($"    emitsAny: {(emitsAny ? "true" : "false")})]");
        w.Line($"{vis} interface {ch.Name}");
        w.Line("{");
        w.Line("}");
        w.Line();
    }

    /// <summary>
    /// Emits a Spek class-side <c>interface</c> as a plain C# interface:
    /// method and property signatures only, base interfaces passed through
    /// verbatim. The no-behavior rule (CE0120) has already rejected any body
    /// or field in semantics, so by the time we get here the members are pure
    /// signatures. Interface members are implicitly public in C#, so no
    /// visibility modifier is emitted.
    /// </summary>
    private static void EmitInterface(InterfaceDecl iface, CSharpWriter w)
    {
        var vis = iface.Visibility == Visibility.Public ? "public" : "internal";
        var typeParams = iface.TypeParameters.Count > 0
            ? $"<{string.Join(", ", iface.TypeParameters.Select(p => p.Name))}>"
            : "";
        var bases = iface.BaseInterfaces.Count > 0
            ? " : " + string.Join(", ", iface.BaseInterfaces.Select(b => b.ToString()))
            : "";

        w.DocComment(iface.DocComment);
        w.Line($"{vis} interface {iface.Name}{typeParams}{bases}{ExpressionEmitter.FormatWhereClauses(iface.WhereClauses)}");
        w.Line("{");
        w.Indent();

        var first = true;
        foreach (var m in iface.Methods)
        {
            if (!first) w.Line();
            w.DocComment(m.DocComment);
            var ret  = m.ReturnType?.ToString() ?? "void";
            var mtp  = m.TypeParameters.Count > 0
                ? $"<{string.Join(", ", m.TypeParameters.Select(p => p.Name))}>"
                : "";
            var parms = string.Join(", ", m.Parameters.Select(FormatSignatureParam));
            w.Line($"{ret} {m.Name}{mtp}({parms}){ExpressionEmitter.FormatWhereClauses(m.WhereClauses)};");
            first = false;
        }

        foreach (var p in iface.Properties)
        {
            if (!first) w.Line();
            w.DocComment(p.DocComment);
            // Accessor bodies/initializers were rejected by CE0120; emit bare
            // `get;` / `set;` / `init;` accessor signatures.
            var accessors = string.Join(" ", p.Accessors.Select(a => $"{a.Kind};"));
            w.Line($"{p.Type} {p.Name} {{ {accessors} }}");
            first = false;
        }

        w.Dedent();
        w.Line("}");
        w.Line();
    }

    private static string FormatSignatureParam(Param p)
    {
        var mod = ExpressionEmitter.ParamModifierKeyword(p.Modifier);
        return mod.Length == 0 ? $"{p.Type} {p.Name}" : $"{mod} {p.Type} {p.Name}";
    }

    /// <summary>
    /// Recursively walks a channel and its base channels,
    /// collecting deduped input and emit message-type names.
    /// Inherited members appear after the channel's own (matches
    /// the linearisation rule from CE0094 / channels-inheritance).
    /// </summary>
    private static void CollectChannelMembers(
        ChannelDecl ch, SymbolTable symbols,
        List<string> inputs, List<string> emits, ref bool emitsAny,
        HashSet<string> seenInputs, HashSet<string> seenEmits)
    {
        foreach (var member in ch.Members)
        {
            switch (member)
            {
                case ChannelInput ci:
                    var inName = ci.MessageType.ToString();
                    if (seenInputs.Add(inName)) inputs.Add(inName);
                    break;
                case ChannelEmits ce when ce.IsAny:
                    emitsAny = true;
                    break;
                case ChannelEmits ce when ce.MessageType is not null:
                    var emName = ce.MessageType.ToString();
                    if (seenEmits.Add(emName)) emits.Add(emName);
                    break;
            }
        }
        foreach (var baseName in ch.BaseChannels)
        {
            var baseChannel = symbols.ResolveChannel(baseName.Simple);
            if (baseChannel is not null)
                CollectChannelMembers(baseChannel, symbols, inputs, emits, ref emitsAny, seenInputs, seenEmits);
        }
    }

    private static void EmitPersistedOverrides(SharedRegionDecl sr, CSharpWriter w)
    {
        // `transient` fields are skipped from both capture and
        // restore. They keep their initialiser value across a restart;
        // the snapshot never carries them.
        // `retired` fields are also skipped: the field is no
        // longer reachable from new code, the persistence store should
        // drop the key on its next save. `deprecated` fields are still
        // captured/restored so existing snapshots roundtrip without
        // data loss while callers migrate off.
        var persistedFields = sr.Fields
            .Where(f => !f.IsTransient && !f.IsRetired)
            .ToList();

        w.Line();
        w.Line("protected override System.Collections.Generic.IReadOnlyDictionary<string, object?> CaptureFields()");
        w.Line("    => new System.Collections.Generic.Dictionary<string, object?>");
        w.Line("    {");
        w.Indent();
        foreach (var f in persistedFields)
            w.Line($"[\"{f.Name}\"] = {f.Name},");
        w.Dedent();
        w.Line("    };");

        w.Line();
        w.Line("protected override void RestoreFields(Spek.Persistence.Snapshot snapshot)");
        w.Line("{");
        w.Indent();
        foreach (var f in persistedFields)
        {
            w.Line($"if (snapshot.Fields.ContainsKey(\"{f.Name}\"))");
            w.Line($"    {f.Name} = snapshot.Get<{f.Type}>(\"{f.Name}\");");
        }
        w.Dedent();
        w.Line("}");
    }

    // Does this type name a Spek runtime type, so the emitted file needs the
    // Spek usings? Sound for the pure-data check above: an enum never does, and
    // a message only does through a field type like `ActorRef`.
    private static bool TypeMentionsSpek(TypeRef t)
    {
        var name = t.Name.ToString();
        if (name.StartsWith("Spek", StringComparison.Ordinal)
            || name is "ActorRef" or "ActorSystem" or "ActorSystemHandle"
                    or "Snapshot" or "FailureDirective" or "Outcome")
            return true;
        return t.TypeArgs.Any(TypeMentionsSpek);
    }

    private static void EmitEnum(EnumDecl e, CSharpWriter w)
    {
        // Default to public so enums can flow through `message` field
        // types, which always emit as public records. An explicit
        // `internal enum` modifier still emits internal — but anyone
        // using it on a message field would trip CS0051 in the
        // generated C#, which is a useful signal at that point.
        var vis = e.Visibility switch
        {
            Visibility.Public    => "public",
            Visibility.Internal  => "internal",
            Visibility.Protected => "protected",
            Visibility.Private   => "private",
            _                    => "public",
        };

        w.DocComment(e.DocComment);
        w.Line($"{vis} enum {e.Name}");
        w.Line("{");
        w.Indent();
        foreach (var m in e.Members)
        {
            w.DocComment(m.DocComment);
            w.Line($"{m.Name},");
        }
        w.Dedent();
        w.Line("}");
        w.Line();
    }

    private static void EmitProgram(ProgramDecl prog, CSharpWriter w)
    {
        // All fields in program scope are local variables — empty field set.
        // Program bodies don't currently use `ask`, so no SymbolTable is
        // threaded here; if that changes, accept it as a parameter.
        var exprEmitter = new ExpressionEmitter(new HashSet<string>());
        var stmtEmitter = new StatementEmitter(w, exprEmitter);

        w.Line($"public static class {prog.Name}Program");
        w.Line("{");
        w.Indent();
        w.Line("public static async System.Threading.Tasks.Task Main(string[] args)");
        stmtEmitter.EmitBlock(prog.Body);
        w.Dedent();
        w.Line("}");
        w.Line();
    }

    // ─── Native tests by convention (`*Tests` module/class in a test project) ──
    private static bool IsTestContainer(TopLevelDecl d) =>
        (d is ModuleDecl m && m.Name.EndsWith("Tests", StringComparison.Ordinal)) ||
        (d is ClassDecl  c && c.Name.EndsWith("Tests", StringComparison.Ordinal));

    // Emits a `*Tests` module/class as an xUnit test class: each public method
    // becomes a `[Spek.Testing.SpekTest]` method (the method name is the test
    // name). A class's fields + `init` (→ a constructor, which the runner runs
    // per test, so state resets between tests) carry per-test setup; non-public
    // methods stay as callable helpers. Bodies run through the normal statement
    // emitter, so they read as ordinary Spek driving a TestActorSystem.
    private void EmitTestContainer(TopLevelDecl decl, CSharpWriter w, SymbolTable symbols)
    {
        var name        = decl is ModuleDecl mod ? mod.Name : ((ClassDecl)decl).Name;
        var exprEmitter = new ExpressionEmitter(new HashSet<string>(), symbols, selfIsThis: true);
        var stmtEmitter = new StatementEmitter(w, exprEmitter);

        // `TestActorSystem` fields are disposed per test (xUnit disposes the test
        // instance after each test), so leaked systems don't accumulate over a run —
        // cleanup without author discipline.
        var disposables = decl is ClassDecl dc
            ? dc.Fields.Where(f => $"{f.Type}".EndsWith("TestActorSystem", StringComparison.Ordinal)).ToList()
            : new List<FieldDecl>();

        w.Line($"public class {name}{(disposables.Count > 0 ? " : System.IDisposable" : "")}");
        w.Line("{");
        w.Indent();
        // A sync test body leaves the async method awaitless — fine for tests.
        w.Line("#pragma warning disable CS1998");
        w.Line();

        IReadOnlyList<MethodDecl> methods;
        if (decl is ClassDecl cls)
        {
            foreach (var f in cls.Fields)
            {
                var fieldInit = f.Initializer != null ? $" = {exprEmitter.Emit(f.Initializer)}" : "";
                w.Line($"{TestMemberVis(f.Visibility)} {f.Type} {f.Name}{fieldInit};");
            }
            if (cls.Fields.Count > 0) w.Line();

            if (cls.Init is { } init)
            {
                var ctorParams = string.Join(", ", init.Parameters.Select(TestFormatParam));
                w.Line($"public {name}({ctorParams})");
                w.Line("{");
                w.Indent();
                foreach (var s in init.Body.Statements) stmtEmitter.EmitStatement(s);
                w.Dedent();
                w.Line("}");
                w.Line();
            }

            foreach (var p in cls.Properties)
            {
                var pvis = TestMemberVis(p.Visibility);
                var accessors = string.Join(" ", p.Accessors.Select(a =>
                {
                    var av = a.Visibility is { } v ? TestMemberVis(v) + " " : "";
                    return a.Body != null
                        ? $"{av}{a.Kind} => {exprEmitter.Emit(a.Body)};"
                        : $"{av}{a.Kind};";
                }));
                var propInit = p.Initializer != null ? $" = {exprEmitter.Emit(p.Initializer)};" : "";
                w.Line($"{pvis} {p.Type} {p.Name} {{ {accessors} }}{propInit}");
            }
            if (cls.Properties.Count > 0) w.Line();

            methods = cls.Methods;
        }
        else methods = ((ModuleDecl)decl).Methods;

        var firstMethod = true;
        foreach (var meth in methods)
        {
            if (!firstMethod) w.Line();
            firstMethod = false;
            var mparams = string.Join(", ", meth.Parameters.Select(TestFormatParam));
            var tps = meth.TypeParameters.Count > 0
                ? $"<{string.Join(", ", meth.TypeParameters.Select(tp => tp.Name))}>"
                : "";
            var mwhere = ExpressionEmitter.FormatWhereClauses(meth.WhereClauses);
            if (meth.Visibility == Visibility.Public)
            {
                // A test — public method → an xUnit fact; the method name is the test name.
                w.Line("[Spek.Testing.SpekTest]");
                w.Line($"public async System.Threading.Tasks.Task {meth.Name}{tps}({mparams}){mwhere}");
                stmtEmitter.EmitBlock(meth.Body);
            }
            else
            {
                var ret = meth.ReturnType?.ToString() ?? "void";
                w.Line($"{TestMemberVis(meth.Visibility)} {ret} {meth.Name}{tps}({mparams}){mwhere}");
                stmtEmitter.EmitBlock(meth.Body);
            }
        }

        if (disposables.Count > 0)
        {
            w.Line();
            w.Line("public void Dispose()");
            w.Line("{");
            w.Indent();
            foreach (var f in disposables) w.Line($"{f.Name}?.Dispose();");
            w.Dedent();
            w.Line("}");
        }

        w.Dedent();
        w.Line("}");
        w.Line("#pragma warning restore CS1998");
        w.Line();
    }

    private static string TestFormatParam(Param p)
    {
        var mod = ExpressionEmitter.ParamModifierKeyword(p.Modifier);
        return mod.Length == 0 ? $"{p.Type} {p.Name}" : $"{mod} {p.Type} {p.Name}";
    }

    private static string TestMemberVis(Visibility v) => v switch
    {
        Visibility.Public    => "public",
        Visibility.Internal  => "internal",
        Visibility.Protected => "protected",
        _                    => "private",
    };
}
